FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["flask", "--app", "app.app_test", "run", "--host=0.0.0.0", "--port=5000", "--cert=./certs/cert.pem", "--key=./certs/key.pem"]