FROM python:3.12-slim

WORKDIR /app

COPY *.py .
COPY requirements.txt .
COPY https /app/https

ENV JWT_PASSWORD=JwtGACHA2425 \
    JWT_LOCATION=headers

RUN pip install -r requirements.txt

EXPOSE 5000

CMD flask --app app_test run --host=0.0.0.0 --port=5000 --cert=./https/cert.pem --key=./https/key.pem