name: Static Analysis

on:
  push:
    branches:
      - main
      
jobs:
  bandit-users:
    name: Account Management Analysis
    runs-on: ubuntu-latest 

    steps:
      # Repo checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install bandit

      - name: Verify Bandit installation
        run: bandit --version

      # Bandit execution
      - name: Run Bandit
        run: bandit -r ./src/users/ -f html -o bandit-report.html --exit-zero --skip B501

      # Report upload
      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: account-management-bandit
          path: bandit-report.html

  bandit-collection:
    name: Collection Analysis
    runs-on: ubuntu-latest 

    steps:
      # Repo checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Check Python version
        run: python --version

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install Bandit
        run: pip install bandit

      - name: Verify Bandit installation
        run: bandit --version

      # Bandit execution
      - name: Run Bandit
        run: bandit -r ./src/collection/ -f html -o bandit-report.html --exit-zero --skip B501

      # Report upload
      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: collection-bandit
          path: bandit-report.html
          
  bandit-market:
    name: Market Analysis
    runs-on: ubuntu-latest 

    steps:
      # Repo checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Check Python version
        run: python --version

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install Bandit
        run: pip install bandit

      - name: Verify Bandit installation
        run: bandit --version

      # Bandit execution
      - name: Run Bandit
        run: bandit -r ./src/market/ -f html -o bandit-report.html --exit-zero --skip B501

      # Report upload
      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: market-bandit
          path: bandit-report.html
