name: Docker Scout Analysis 2.0

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

   push-and-analize:
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # Step 4: Setup Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker build -t collection_db_manager src/collection/collection_db_manager
        docker build -t edit_gacha_collection src/collection/edit_gacha_collection
        docker build -t roll_gacha src/collection/roll_gacha
        docker build -t see_gacha_collection src/collection/see_gacha_collection
        docker build -t auction_market src/market/auction_market
        docker build -t market_db_manager src/market/dbm
        docker build -t trading_history src/market/trading_history
        docker build -t account_management src/users/account_management
        docker build -t users_db_manager src/users/db_manager

    - name: Tag images
      run: |
        docker tag collection_db_manager:latest nicolastaniscia/ase_project_24-25:latest
        docker tag edit_gacha_collection:latest nicolastaniscia/ase_project_24-25:latest
        docker tag roll_gacha:latest nicolastaniscia/ase_project_24-25:latest
        docker tag see_gacha_collection:latest nicolastaniscia/ase_project_24-25:latest
        docker tag auction_market:latest nicolastaniscia/ase_project_24-25:latest
        docker tag market_db_manager:latest nicolastaniscia/ase_project_24-25:latest
        docker tag trading_history:latest nicolastaniscia/ase_project_24-25:latest
        docker tag account_management:latest nicolastaniscia/ase_project_24-25:latest
        docker tag users_db_manager:latest nicolastaniscia/ase_project_24-25:latest

    - name: Push on Docker Hub
      run: docker push nicolastaniscia/ase_project_24-25:latest
